title: Nguyen P Bich Ngoc
logo: assets/img/profilepic-fotor-20240904163233.png
description: Aspiring Data Scientist Intern with a passion for Data Analysis and Machine Learning
# show_downloads: true
theme: jekyll-theme-minimal
